export const WHITE_NEUTRAL = "#ffffff";
export const DARK_GREEN = "#006400";
export const LIGHT_GREEN = '#8FBC8F';
export const DARK_GRAY = '#2F4F4F';
export const LIGHT_GRAY = '#D3D3D3';
export const BEIGE = '#DED9AF' ; 
export const LIGHT_BLUE = '#ADD8E6';
export const DARK_BLUE = '#1F4E79';
export const PALE_YELLOW = '#FFFACD';